### ISSUE TITLE
table of contents on side bar

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.repex.at#56]
For RepEx documentation we should have a table of contents in the left side bar. We don't have it currently. See: http://repex.readthedocs.org/en/devel-antons/pages/installation.html

A table of contents make it easier to navigate. 

As an example of the table of contents, please see:
http://radicalensemblemd.readthedocs.org/en/devel/user_guide/getstarted.html

**Comment by antonst** [comment]
> For RepEx documentation we should have a table of contents in the left side bar. We don't have it currently

This is not true, the reason why for Installation section there is no table of contents is because there is only one section. If you would go for example to previous section of the same documentation version you have referenced above: http://repex.readthedocs.org/en/devel-antons/pages/introduction.html you would get a table of contents on the left.
